# Generated by Django 3.0.2 on 2020-03-20 15:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalprotectevent',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='globalprotectevent',
            name='event',
        ),
        migrations.AddField(
            model_name='globalprotectevent',
            name='login_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='globalprotectevent',
            name='login_event',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='globalprotectevent',
            name='logout_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='globalprotectevent',
            name='logout_event',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='globalprotectevent',
            name='user',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
    ]
